# Generated by Django 3.0.3 on 2021-07-09 15:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('account_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('balance', models.BigIntegerField()),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiver_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Customer')),
                ('sender_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='bank.Customer')),
            ],
        ),
    ]
